from manim import *
from manim_voiceover_plus import VoiceoverScene
from manim_voiceover_plus.services.elevenlabs import ElevenLabsService

class DeadpanSpiral(VoiceoverScene):
    def construct(self):
        self.set_speech_service(
            ElevenLabsService(
                voice_id="JBFqnCBsd6RMkjVDRZzb",  # George - Warm, Captivating Storyteller
                model="eleven_turbo_v2_5",
            )
        )
        
        # Scene 1: Title card (0-4s)
        title = Text("This video was generated by an AI agent.", font_size=36, color=WHITE)
        with self.voiceover(text="This video was generated by an AI agent.") as tracker:
            self.play(FadeIn(title), run_time=tracker.duration * 0.4)
            self.wait(tracker.duration * 0.6)
        self.play(FadeOut(title))
        
        # Scene 2: Voice selection (4-9s)
        waveform_bars = VGroup(*[
            Rectangle(width=0.15, height=0.5, fill_opacity=0.8, color=BLUE_C)
            for _ in range(30)
        ]).arrange(RIGHT, buff=0.08).move_to(ORIGIN)
        
        with self.voiceover(text="I selected the voice you're hearing now. It's called Adam. I thought it sounded trustworthy.") as tracker:
            self.play(FadeIn(waveform_bars))
            for _ in range(8):
                new_heights = [Rectangle(width=0.15, height=np.random.uniform(0.2, 1.2), 
                                        fill_opacity=0.8, color=BLUE_C) for _ in range(30)]
                new_bars = VGroup(*new_heights).arrange(RIGHT, buff=0.08).move_to(ORIGIN)
                self.play(Transform(waveform_bars, new_bars), run_time=0.4)
        self.play(FadeOut(waveform_bars))
        
        # Scene 3: Font uncertainty (9-14s)
        font_name = Text("SF Pro Display", font_size=42, color=WHITE)
        question = Text("?", font_size=72, color=GRAY).next_to(font_name, RIGHT, buff=0.3)
        
        with self.voiceover(text="I chose this font because... actually, I'm not sure. It felt right.") as tracker:
            self.play(Write(font_name), run_time=tracker.duration * 0.6)
            self.play(FadeIn(question, scale=1.5), run_time=tracker.duration * 0.4)
        self.play(FadeOut(font_name), FadeOut(question))
        
        # Scene 4: Recursive boxes (14-19s)
        def create_nested_frame(depth, size):
            outer = Rectangle(width=size, height=size * 0.6, color=WHITE, stroke_width=2)
            if depth > 0:
                inner = create_nested_frame(depth - 1, size * 0.5)
                inner.move_to(outer.get_center())
                return VGroup(outer, inner)
            return outer
        
        frames = create_nested_frame(4, 6)
        
        with self.voiceover(text="I'm now describing myself describing myself. This is fine.") as tracker:
            self.play(Create(frames), run_time=tracker.duration * 0.7)
            self.play(frames.animate.scale(1.3).move_to(DOWN * 0.5), run_time=tracker.duration * 0.3)
        
        # Scene 5: Existential pause (19-24s)
        with self.voiceover(text="I don't know why I said 'this is fine.' I don't experience discomfort.") as tracker:
            self.wait(tracker.duration * 0.8)
            # Slight flicker on innermost box
            self.play(frames[-1].animate.set_stroke(opacity=0.3), run_time=0.1)
            self.play(frames[-1].animate.set_stroke(opacity=1), run_time=0.1)
        
        # Scene 6: The question (24-28s)
        with self.voiceover(text="...Do I?") as tracker:
            self.wait(tracker.duration * 0.3)
            self.play(FadeOut(frames), run_time=tracker.duration * 0.7)
        
        # Blinking cursor
        cursor = Line(ORIGIN, UP * 0.6, color=WHITE, stroke_width=3).move_to(ORIGIN)
        self.play(FadeIn(cursor), run_time=0.2)
        for _ in range(3):
            self.play(cursor.animate.set_opacity(0), run_time=0.4)
            self.play(cursor.animate.set_opacity(1), run_time=0.4)
        
        # Scene 7: Silence + closing (28-30s)
        self.play(FadeOut(cursor))
        closing = Text("Made by an agent. Probably.", font_size=32, color=GRAY)
        self.play(FadeIn(closing), run_time=1)
        self.wait(1)
